### ISSUE TITLE
Look at/integrate DynamicLinq+

### ISSUE THREAD

**Issue by programcsharp** [kahanu/System.Linq.Dynamic#13] opened 2014-12-04 15:37 UTC
I just ran across this project: https://code.google.com/p/dynamic-linq/ -- looks to have not been updated in awhile, but it adds some nice features to DynamicLinq:

 - new Namespace.Type(expr as property_name) grammar
 - new @0(expr as property_name) with Type given as placeholder grammar, i.e Select("new @0(.....)", typeof(SomeType))
 - Select<OutputType>("....") which returns IQueryable<OutputType> and makes sure the result of select is actually assignable to OutputType
 - OutputType of Select<OutputType> visible in query under @out symbol - Select<OutputType>("new @out (....)")
 - GroupBy<KeyType, ValType>("....", "....") available similarly Select<>
 - other GroupBy variants
 - inferred it for indexers - i.e. [0] > 10 equivalent to it[0] > 10
 - parentheses can be omitted when invoking argument-less lambda or aggregate
 - delegates can be passed for placeholder where lambda expression are expected.
 - eval operator which evaluates DynamicLinq language from string, e.g. `Where("some_prop = eval @0", "10 + other_prop");
 - Anonymous types in new operator can implement an interface - syntax: new IInterface (expr as prop, ...).

I don't have time to integrate it right now, but it might be worth looking into at some point. Just wanted to note it here so I don't forget :-)

**Comment by Kagamine** [comment] 2015-02-13 07:45
Operator '=' incompatible with operand types 'Int32' and 'String' 
where can I make a force convertion in 'System.Linq.Dynamic'?

**Comment by kahanu** [comment] 2015-02-13 07:52
Unless I misunderstand you, this isn't a Dynamic issue, you still need to cast the object to the correct type that you want.

**Comment by Kagamine** [comment] 2015-02-13 07:55
but in my project, the arguments are gained from Request.QueryString, and the type of them are System.String. If I just insert the params into expression without 'params object[]' it may cause inject problem. I want to write some lines to make a force convertion.

**Comment by Kagamine** [comment] 2015-02-13 08:01
![qq20150213-1](https://cloud.githubusercontent.com/assets/2216750/6184142/3b2e302e-b399-11e4-9c89-17ba291b25d1.png)
the '$id' means it will get the Request.QueryString["id"] into here.
so, the problem is type incompatible
![qq20150213-2](https://cloud.githubusercontent.com/assets/2216750/6184160/713f80dc-b399-11e4-88ec-9b6afcd812b9.png)
![qq20150213-3](https://cloud.githubusercontent.com/assets/2216750/6184168/817f6700-b399-11e4-9ceb-dd828022e066.png)

**Comment by Kagamine** [comment] 2015-02-13 08:06
Dynamic Linq can distinguish type of left and right, then can I make a force conversion?

**Comment by kahanu** [comment] 2015-02-13 08:06
@Kagamine - I see your problem, but since I didn't author the Dynamic library, I only have two suggestions: 1) see if adding a DataType attribute to the property of type Int32 will force the conversion, 2) post your issue on stackoverflow.com.  You would probably get a better answer there.

Sorry I couldn't be more help.

**Comment by Kagamine** [comment] 2015-02-13 08:08
thanks.. I just try to write some lines to make a force conversion, but the source is so complex...QAQ

**Comment by ryanvgates** [comment] 2015-09-11 18:03
@Kagamine it sounds like your issue was entirely separate from the original issue above. In the future, please create a separate issue.

**Comment by ryanvgates** [comment] 2015-09-11 18:05
@programcsharp @kahanu I think the integration will most likely have to wait quite a while since the code bases are different enough to make integration challenging. Would either of you mind if I closed this issue for now?

**Comment by programcsharp** [comment] 2015-09-11 18:23
Sure, if that makes things easier. I've been pulling things back and forth by hand as needed.

For future reference, looks like the project has moved from google code to https://github.com/mrKrizz/dynamic-linq/tree/master. @mrkrizz might be interested in the integration.

**Comment by ryanvgates** [comment] 2015-09-11 19:20
@programcsharp yes for right now it would. I'm trying to get through all the stale issues and pull requests. I agree that there is a good case for integration. I just want to be realistic regarding what is considered active. I think it will take some time before I can move forward on the integration.

**Closed by ryanvgates** 2015-09-11 19:20 UTC
